---
name: Ruff

on: [push, pull_request]

# jobs:
#   check:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: chartboost/ruff-action@v1

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: |
          sudo apt install pipx
          pipx install ruff


      - name: Run ruff
        run: ruff check archiveyoutube.py
